FROM gcc:9.2.0

COPY gitbuild.sh .

RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3.tar.gz
RUN tar -zxvf cmake-3.16.3.tar.gz && cd cmake-3.16.3 && ./bootstrap && make && make install && make clean